sudo: false

addons:
    apt:
      packages:
       - make
       - cmake-data
       - cmake
    homebrew:
      packages:
      - ccache
      
git:
  depth: false    
  

language: cpp

compiler:
    - gcc
    - clang

os:
  - linux
  - osx
  

before_script:
  - mkdir -p travis_root
  - cd travis_root
  - rm -rf ughub
  - git clone https://www.github.com/UG4/ughub
  - mkdir ug4
  - cd ug4
  - ../ughub/ughub init .
  - ../ughub/ughub install ugcore 
  - ../ughub/ughub add 
  - ../ughub/ughub addsource neurobox https://github.com/NeuroBox3D/neurobox-packages
  - ../ughub/ughub install neuro_collection
  - mkdir build
  - cd build
  - cmake ../ -DDIM=3 -DCPU=1 -DLAPACK=OFF -DBLAS=OFF -DENABLE_ALL_PLUGINS=ON -DPARALLEL=OFF
  - travis_wait 45 make -j2

script:
   - cd ../../../
   - git clone https://github.com/NeuroBox3D/neuromorpho
   - cd neuromorpho
   - mkdir -p TestCell/44-4.CNG
   - python get_swc.py --name 44-4
   - git clone https://github.com/stephanmg/vr-grids
   - ./vr-grids/Code/pipeline_vr.sh -i 44-4.CNG.swc -o TestCell -d true
