sudo: false

addons:
    apt:
      packages:
       - make
       - cmake-data
       - cmake
    homebrew:
      packages:
      - ccache
      
git:
  depth: false    
  

language: cpp

compiler:
    - gcc
    - clang

os:
  - linux
  - osx
  

before_script:
  - mkdir -p travis_root
  - cd travis_root
  - rm -rf ughub
  - git clone https://www.github.com/UG4/ughub
  - mkdir ug4
  - cd ug4
  - ../ughub/ughub init .
  - ../ughub/ughub install ugcore 
  - ../ughub/ughub add 
  - ../ughub/ughub addsource neurobox https://github.com/NeuroBox3D/neurobox-packages
  - ../ughub/ughub install neuro_collection
  - mkdir build
  - cd build
  - cmake ../ -DDIM=3 -DCPU=1 -DLAPACK=OFF -DBLAS=OFF -DENABLE_ALL_PLUGINS=ON -DPARALLEL=OFF
  - travis_wait 45 make -j2

script:
   - cd ../../../
   - git clone https://github.com/NeuroBox3D/neuromorpho
   - cd neuromorpho
   - mkdir -p TestCell/44-4.CNG
   - python get_swc.py --name 44-4
   - ./travis_root/ug4/bin/ugshell -call "test_import_swc_and_regularize(\"44-4.CNG.swc\", \"8\", \"user\", 0, false, true)"
   - ./travis_root/ug4/bin/ugshell -call  "test_import_swc_general_var_for_vr_var(\"new_strategy.swc\", false, 0.5, true, 8, 0, true, 1, \"identity\", \"-1\")" 
